<?php

use App\Models\Club;
use App\Models\User;
use Illuminate\Foundation\Testing\WithoutMiddleware;
use Illuminate\Foundation\Testing\DatabaseMigrations;
use Illuminate\Foundation\Testing\DatabaseTransactions;

class UserTest extends TestCase
{
    use DatabaseTransactions;


    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

    }

    /** @test */
    public function get_list_of_active_users() {
        $clubUsers = Club::find(1)->userClubs->where('date_left', null);
        $this->assertGreaterThan(0, count($clubUsers));
        $user = User::find(1)->with('userClubs', 'userClubs.club')->get();
        dd($user);
    }

    /** @test */
    //public function delete_user() {
    //    $user = factory(User::class)->create();
    //    $this->assertGreaterThan(0,$user->id);
    //    $club = Club::inRandomOrder()->first();
    //    $user->userClubs()->save($club);
    //    $userClub = $user->userClub();
    //    $user->delete();
    //    $this->assertNotNull($user->deleted_at);
    //}
}
